package com.opsmind.identity.domain.audit;

/** 02-business-invariants INV-UA-006: one action per application-service write path SPEC-UA-001 builds. Extended as later specs add more. */
public enum IdentityAuditAction {
    USER_IDENTITY_LINKED,
    USER_IDENTITY_DISABLED,
    USER_IDENTITY_ENABLED,
    USER_IDENTITY_DEPROVISIONED,
    USER_IDENTITY_SYNCED,
    ROLE_ASSIGNMENT_GRANTED,
    ROLE_ASSIGNMENT_REVOKED,
    ROLE_ASSIGNMENT_EXPIRED,
    USER_SESSION_STARTED,
    USER_SESSION_REVOKED,
    USER_SESSION_EXPIRED,
    USER_SESSION_COMPROMISED,
    USER_SESSION_TERMINATED,
    STEPUP_REQUESTED,
    STEPUP_VERIFIED,
    STEPUP_CONSUMED,
    STEPUP_FAILED,
    STEPUP_EXPIRED,
    STEPUP_CANCELLED,
    SERVICE_IDENTITY_REGISTERED,
    SERVICE_IDENTITY_DISABLED,
    SERVICE_IDENTITY_RETIRED,
    AUTHORIZATION_DECISION_EVALUATED
}
