package com.opsmind.identity.domain.audit;

/** 02-business-invariants INV-UA-006: one action per application-service write path SPEC-UA-001 builds. Extended as later specs add more. */
public enum IdentityAuditAction {
    USER_IDENTITY_LINKED,
    USER_IDENTITY_DISABLED,
    USER_IDENTITY_ENABLED,
    USER_IDENTITY_DEPROVISIONED,
    USER_IDENTITY_SYNCED,
    ROLE_ASSIGNMENT_GRANTED,
    ROLE_ASSIGNMENT_ACTIVATED,
    ROLE_ASSIGNMENT_REVOKED,
    ROLE_ASSIGNMENT_EXPIRED,
    ROLE_ASSIGNMENT_CANCELLED,
    USER_SESSION_STARTED,
    USER_SESSION_REVOKED,
    USER_SESSION_EXPIRED,
    USER_SESSION_COMPROMISED,
    USER_SESSION_TERMINATED,
    STEPUP_REQUESTED,
    STEPUP_VERIFIED,
    STEPUP_CONSUMED,
    STEPUP_FAILED,
    STEPUP_EXPIRED,
    STEPUP_CANCELLED,
    SERVICE_IDENTITY_REGISTERED,
    SERVICE_IDENTITY_DISABLED,
    SERVICE_IDENTITY_RETIRED,
    SERVICE_IDENTITY_VALIDATED,
    AUTHORIZATION_DECISION_EVALUATED,
    PERMISSION_DENIED,
    BREAK_GLASS_ACTIVATED,
    BREAK_GLASS_ACTIVATION_DENIED,
    BREAK_GLASS_REVOKED,
    BREAK_GLASS_EXPIRED,
    /** SPEC-UA-031 (07-data-model: "Email/display name may be encrypted and erased by retention"). */
    USER_IDENTITY_PII_REDACTED,
    /** SPEC-UA-031 (11-security: audit access is itself audited). */
    AUDIT_RECORDS_QUERIED
}
